In [1]:
import numpy as np

In [5]:
x = np.array([1, 2, 3, 4])
x

array([1, 2, 3, 4])

# Adding New Axis (Expanding Dimensionality)

In [6]:
x[np.newaxis].T

array([[1],
       [2],
       [3],
       [4]])

In [7]:
np.expand_dims(x, -1)

array([[1],
       [2],
       [3],
       [4]])

# Rounding

In [8]:
from math import ceil, floor

In [9]:
floor(3)

3

In [10]:
ceil(3)

3

In [11]:
a = np.array([[0, 2], [3, 4]])
x = a.flat
x[x > 0]

array([2, 3, 4])

In [47]:
x = 1
y = 1
theta = 5*np.pi/4

In [48]:
x * np.cos(theta) + y * np.sin(theta)

-1.4142135623730951

In [49]:
np.sqrt(1 + 1)

1.4142135623730951

In [44]:
d = np.array([-1 , 2, -3, 2])
d[d < 0] = 0
d

array([0, 2, 0, 2])

In [52]:
np.pi/8

0.39269908169872414

In [53]:
np.max((1, 2))

2

In [18]:
m = np.array([[1, 2 ,3], [3, 4, 5], [1, 3, 5], [1, 7, 2]])
print(np.min(m, axis=0))
print(np.max(m, axis=0))

[1 2 2]
[3 7 5]


In [29]:
centers = np.random.uniform(np.min(m, axis=0), np.max(m, axis=0), [2, 3])

In [34]:
np.linalg.norm(m - centers[0], axis=1)

array([1.49483199, 2.0194474 , 1.71784806, 4.5096325 ])

In [3]:
np.ones(4)/4

array([0.25, 0.25, 0.25, 0.25])

In [5]:
np.diag(np.ones(4))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
from scipy.stats import multivariate_normal

In [15]:
norm.pdf(np.array([1, 1]), loc=np.array([1, 1]), scale=np.array([[1, 0], [0, 1]]))

array([[0.39894228,        nan],
       [       nan, 0.39894228]])

In [20]:
multivariate_normal.pdf(np.array([[0, 0], [1, 1]]), mean=np.array([1, 1]), cov=np.array([[1, 0], [0, 1]]))

array([0.05854983, 0.15915494])

In [5]:
x = np.array([[1, 2, 3], [1, 1, 1]])
x

array([[1, 2, 3],
       [1, 1, 1]])

In [9]:
np.linalg.norm(x, axis=0)

array([1.41421356, 2.23606798, 3.16227766])

In [22]:
y, x = np.mgrid[:3,:5]
xy = np.stack([x, y], axis=-1)

In [23]:
y

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2]])

In [24]:
x

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [25]:
xy

array([[[0, 0],
        [1, 0],
        [2, 0],
        [3, 0],
        [4, 0]],

       [[0, 1],
        [1, 1],
        [2, 1],
        [3, 1],
        [4, 1]],

       [[0, 2],
        [1, 2],
        [2, 2],
        [3, 2],
        [4, 2]]])

In [6]:
r = np.random.randn(100,3, 4)
r.shape

(100, 3, 4)

In [7]:
H, edges = np.histogramdd(r, bins = (5, 8, 4))

H.shape, edges[0].size, edges[1].size, edges[2].size

ValueError: too many values to unpack (expected 2)

In [8]:
np.linspace(0, 255, 10)

array([  0.        ,  28.33333333,  56.66666667,  85.        ,
       113.33333333, 141.66666667, 170.        , 198.33333333,
       226.66666667, 255.        ])

In [3]:
np.zeros([*np.array([5, 3]), 2], dtype=np.float32)

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]], dtype=float32)

In [23]:
    i_cell = np.mgrid[:5, :3] // 5
    i_cell.shape
    #np.add.at(hog, tuple([*i_cell, i_bin]), grad_mag)

(2, 5, 3)

4.0

In [91]:
x = np.mgrid[:20, :30] // 5
x.shape

(2, 20, 30)

In [94]:
x[1, 10, 15]

3